### PR TITLE
fix(refs): Pull before grabbing refs

### PR DESCRIPTION
**Pull request by khankuan**
Local repo needs to be updated before checking tags.

### CODE REVIEW

**Comment by finom** [comment]
Hmm.. It's expected that a local repo is up to date: CI pulls latest version, makes needed checks (e. g. runs needed tests) and semantic-release makes a decision. I'm not sure why do we need to pull repo twice.

Also CI creates some artifacts and semantic-release changes package.json so they need to be committed and ``git pull`` will probably throw an error.

I'm confused. Can you explain what's the usecase of this and give a link to a repo and Travis build which uses this approach?

**Comment by khankuan** [comment]
I was trying to run it locally without ci. After the first successful release, my local machine doesn't seem to have the latest tags. After I committed new changes and try to release, it uses the old tag which caused tag invalid error because it's creating the same tag. The error resolved once I pulled and have the latest tags.

**Comment by finom** [comment]
Then pull manually (add ``git pull`` to NPM scripts for example). Your solution probably breaks current functionality. Before making any pull request check your code operability on CI please.

**Comment by khankuan** [comment]
Agreed

**Pull request closed without merging**
